### PR TITLE
Added 'hour' parameter to 'forecast' method and 'end_dt' parameter to 'history' method.

### PR DESCRIPTION
**Pull request by mikelexp**

### CODE REVIEW

**Comment by andreiavrammsd** [comment]
Hi, @mikelexp,

Where did you find those params? I don't see them in the API https://www.apixu.com/api-explorer.aspx
Do you have a paid license?

Thanks!

**Comment by mikelexp** [comment]
@andreiavrammsd Yes, I have a paid license, but those parameters are in the official documentation, in the Request section: https://www.apixu.com/doc/request.aspx

**Comment by andreiavrammsd** [comment]
Those two params don't get me different responses, I guess they are used for paid licenses. The API was implemented with a free license, so we'll have to wait until I get a paid one from Apixu so I can fully test. 

Meanwhile, could you run the [QA tools](https://github.com/apixu/apixu-php#development) over the code and update the tests? If you can't do it, please let me know and I will handle this.

**Comment by andreiavrammsd** [comment]
I've added the missing params in #13 and released [v1.2.0](https://github.com/apixu/apixu-php/releases/tag/v1.2.0).

Thank you!

**Pull request closed without merging**
